molecules-message作成
nftbit/takumi-frontend-basic-last-assignment pull request #4
Opened 2023-02-24 08:26 UTC by nftbit

## セルフチェック
- [○ ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ ○] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ ○] 記述の重複はないか

2023-02-24 08:31 UTC, higashiji2000 requested changes

2023-02-24 08:31 UTC, higashiji2000 commented on src/stories/molecules-message.stories.js
> +import "../components/molecules/massage/message.scss";
```suggestion
import Item_Message from "../components/molecules/message/message.html";
import "../components/molecules/message/message.scss";
```

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +    <p class="small">説明テキスト</p>
![image](https://user-images.githubusercontent.com/104500220/221340177-8217b9ef-1431-4791-8d3e-dd58a3f88281.png)
pタグにデフォルトでついているmarginをなくしてほしいので`margin:0`で打ち消してください。

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  }
この`.up`の機能は`.message`に持たせていいです。つまり、`.message`が親で、`<h4>`と`<p>`が子という構造になります。ちなみに、`h1`はページで一つしか使ってはいけないのですが、`h2`以下は特に制約ないので、ここでは`h2`で大丈夫です。

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +  </div>
ふたつつくるのではなく、メディアクエリを用いて画面幅でこの2パターンが切り替わるようにしてください。つまり、htｍlは`.message`が親で、`<h4>`と`<p>`が子という構造で、スタイルの切り替えはscssで行います

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +  .h6 {
おそらく上記の変更の結果からこの部分は削除されるとは思いますが
×`.h6`=h6というクラス名（今のままだとスタイルが当たっていないはず）
◎`h6`=h6というタグ名

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +    <p class="small">説明テキスト</p>
今回はpタグ一つしかないので、クラス名は不要かなと思います。
scssのネストの形の中で、pタグにスタイルを付与すればOKです

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    font-size: 36px;
フォントサイズは`variables`というファイルの中にあらかじめ変数として定められているので`$`を使う形で変数で書きましょう

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    font-family: "Noto Serif JP";
font-familyも同様に変数が存在します

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    color: #000000;
colorも同様に変数があります

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    align-items: center;
`display:flex`は親要素に対して付与し、子要素に効かせるためのものですが、`.small`は子要素を持たないので不要です

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    text-align: center;
`text-align:center;`だけで十分だと思います
開発者ツールを参考にスタイルの付け外しをしてみて、最小限の記述で済むよう心がけてみましょう
参考資料：[開発者ツールの使い方](https://playground.wraptas.site/67db90c0263c44d58b966b5f23f69917)

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +    <h4>タイトルテキスト</h4>
画面幅が小さい時と大きい時ともに、Figmaを参考に`margin-bottom`を修正しましょう
また明朝体なので、こちらも変数を参照の上設定お願いします（ちなみに、デフォルトはゴシックなので、ゴシックの部分に対してはフォントのスタイル当てなくてデフォルトのままでOKです）
![image](https://user-images.githubusercontent.com/104500220/221340686-122c0297-ed89-48b0-9d5d-6ef380a1756f.png)
![image](https://user-images.githubusercontent.com/104500220/221340709-ee2ac9df-b646-454b-b5e3-59b72d60503f.png)

2023-02-25 05:47 UTC, MinamiHotta commented on src/components/molecules/message/message.scss
> +    align-items: center;
![image](https://user-images.githubusercontent.com/104500220/221340794-22dc8d93-d9fb-4e9b-98be-761deab5e380.png)
Figmaの右サイドバーのTypographyを見れば載っています

2023-02-25 06:29 UTC, MinamiHotta commented on src/components/molecules/message/message.html
> +  </div>
planでやってくださっていたのと同じ書き方です

2023-03-22 04:46 UTC, SakaueYae reviewed
指摘されていた箇所がほぼ完ぺきに修正されていて、素晴らしいです👏あと数か所修正をお願いします！

2023-03-22 04:46 UTC, SakaueYae commented on src/components/molecules/message/message.scss
> +  }
messageクラスにスタイルを付与するときは直接`.message`の中に書きましょう！この書き方ですと、messageクラスの中にある子要素のmessageクラスを指定しており、そのような要素が存在しないため今のままではスタイルが適用されていません！

2023-03-22 04:46 UTC, SakaueYae commented on src/components/molecules/message/message.scss
> +  .title_text {
![image](https://user-images.githubusercontent.com/101164626/226802496-3e2364d7-dad7-4cfb-a0d8-d2bc59b06b75.png)
画面幅がlg以上のときの下の余白の追加をお願いします！

2023-03-22 04:46 UTC, SakaueYae commented on src/components/molecules/message/message.scss
> +    font-family: $fontfamily-gothic;
![image](https://user-images.githubusercontent.com/101164626/226802833-bec10f6a-6bce-477a-acd1-59f02310a08d.png)
検証ツールで確認してみると分かるかと思うのですが、デフォルトのフォントがゴシック体で指定されているため、ここでの指定は無くても大丈夫です！
https://github.com/nftbit/takumi-frontend-basic-last-assignment/pull/4#discussion_r1117871175

2023-03-22 04:46 UTC, SakaueYae commented on src/components/molecules/message/message.scss
> +    color: $black;
このままでも問題はないですが、`.message`の中でフォントの色を指定してあげると子要素すべてに適用されるので、`.title_text`と`.small`でそれぞれ指定してあげるよりも楽でおすすめです✨

2023-03-27 01:48 UTC, higashiji2000 approved these changes
見た目的には問題ないのでLGTMです

2023-03-27 01:48 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +  overflow-wrap: normal;
overflow-wrapは初期値が `normal` なので、この行は不要です

2023-03-27 01:48 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +    font-weight: 400;
この2行も初期値だと思います！

2023-03-27 01:48 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +    overflow-wrap: normal;
こちらも同様です

2023-04-01 13:20 UTC, merged